"""
Notion database IDs — regenerated on first setup, then persisted.

This file is generated by the setup flow when connecting to a new Teamspace.
See notion/setup.py for the setup process.
"""

# Database IDs for the current Notion Teamspace
NOTION_SONGS_DB_ID = "33341983-beb5-81dd-aac1-c020d8f39de3"
NOTION_ARTISTS_DB_ID = "33341983-beb5-81d1-b3b4-f73dac267068"
NOTION_PLAYLISTS_DB_ID = "33341983-beb5-81de-bc40-f6832e00a3b4"
NOTION_PLAYLIST_SONGS_DB_ID = "33341983-beb5-811f-9093-e957a87ca491"

# Parent page ID where MusicTunnel and databases are created
# If set, will be used by default for setup (no need to prompt)
NOTION_PARENT_PAGE_ID = "33341983beb580858258fee89fc7dbc5"

# Database name → schema filename mapping
DB_NAMES = {
    "Songs": "songs.json",
    "Song Artists": "song_artists.json",
    "Playlists": "playlists.json",
    "Playlist Songs": "playlist_songs.json",
}
